site_name: RetroDECK Wiki
nav:
  - Home: index.md
  - About RetroDECK:
    - What is RetroDECK?: wiki_about/what-is-retrodeck.md
    - What is included?: wiki_about/what-is-included.md
    - Beta Period: wiki_about/beta-period.md
    - Visions & Goals: wiki_about/visions-and-goals.md
    - Story & Philosophy: wiki_about/story-philosophy.md
    - The Team & Credits: wiki_about/team-credits.md
theme: readthedocs
