site_name: RetroDECK Wiki
nav:
  - Home: index.md
  - About RetroDECK:
    - What is RetroDECK?: wiki_about/what-is-retrodeck.md
    - Visions & Goals: wiki_about/visions-and-goals.md
theme: readthedocs
