site_name: RetroDECK Wiki
site_description: The Official RetroDECK Wiki
navigation_depth: 5
nav:
  - Wiki Home 🏠: index.md
  - General Information 📰:
    - What is RetroDECK?: wiki_general/what-is-retrodeck.md
    - What is included in RetroDECK?: wiki_general/what-is-included.md
    - Supported Systems: wiki_general/supported-systems.md
    - RetroDECK Configurator: wiki_general/configurator.md
    - The RetroDECK Beta: wiki_general/beta-period.md
    - FAQ - Frequently Asked Questions: wiki_howto_faq/faq.md
    - Known Issues: wiki_general/known-issues.md

  - How-to's ❔:
    - How-to - Move RetroDECK to a new device: wiki_howto_faq/move-retrodeck.md
    - How-to - Add RetroDECK to Steam: wiki_howto_faq/add-to-steam.md
    - How-to - Enable Controllers in Steam: wiki_howto_faq/enable-controllers-steam.md

  - Steam Deck:
    - Steam Deck - Installation and Updates: wiki_devices/steamdeck/steamdeck-start.md
    - Steam Deck - Optimizations: wiki_devices/steamdeck/steamdeck-optimize.md
    - Steam Deck - Software Recommendations: wiki_devices/steamdeck/steamdeck-software.md

  - Linux Desktop:
    - Linux Desktop - Installation and Updates: wiki_devices/linux_desktop/linux-install.md
    - Linux Desktop - Software Recommendations: wiki_devices/linux_desktop/linux-software.md

  - Controllers and Input 🎮:
    - RetroDECK with Steam Input: wiki_controllers/about-steam-input.md
    - Button Prompts in Games: wiki_controllers/diffrent-game-inputs.md
    - Steam Deck Controls: wiki_controllers/controls-steamdeck.md
    - Playstation Controllers (WIP): wiki_controllers/controllers-playstation.md

  - Development🔎:
    - Current Version: wiki_rd_versions/version_0.7b/0.7.4b/
    - Version History (Patchnotes): wiki_rd_versions/version-history.md
    - Folders and Filepaths: wiki_development/folders-filepaths.md
    - CLI Guide: wiki_development/cli-guide.md
    - Development Notes: wiki_development/general-development.md

  - Community and Helping ❤️:
    - Discord: wiki_community/discord.md
    - Lemmy/Reddit: wiki_community/lemmy-reddit.md
    - How to Contribute to RetroDECK?: wiki_community/contibute-rd
    - How to help out with testing?: wiki_community/testing-rd.md

  - About RetroDECK 📖:
    - The Team & Credits: wiki_about/team-credits.md
    - Story & Philosophy: wiki_about/story-philosophy.md
    - Visions & Goals: wiki_about/visions-and-goals.md
    - Donations & Licenses: wiki_about/donations- licenses.md
theme: readthedocs
