site_name: RetroDECK Wiki
nav:
  - Home: index.md
  - General Information:
    - What is RetroDECK?: wiki_general/what-is-retrodeck.md
    - What is included in RetroDECK?: wiki_general/what-is-included.md
    - The RetroDECK Beta: wiki_general/beta-period.md

  - About RetroDECK:
    - Visions & Goals: wiki_about/visions-and-goals.md
    - Story & Philosophy: wiki_about/story-philosophy.md
    - The Team & Credits: wiki_about/team-credits.md
    - Donations & Licenses: wiki_about/donations- licenses.md

theme: readthedocs
