site_name: RetroDECK Wiki
nav:
  - Home: index.md
  - General Information 📰:
    - What is RetroDECK?: wiki_general/what-is-retrodeck.md
    - What is included in RetroDECK?: wiki_general/what-is-included.md
    - Supported Systems: wiki_general/supported-systems.md
    - The RetroDECK Beta: wiki_general/beta-period.md
    - Known Issues: wiki_general/known-issues.md

  - About RetroDECK 📖:
    - The Team & Credits: wiki_about/team-credits.md
    - Story & Philosophy: wiki_about/story-philosophy.md
    - Visions & Goals: wiki_about/visions-and-goals.md
    - Donations & Licenses: wiki_about/donations- licenses.md

  - FAQ and How-to's ❔:
    - FAQ - Frequently Asked Questions: wiki_faq_howto/faq.md

  - Community 💬:
    - Community Rules: wiki_community/community-rules.md

  - Helping out 🫶:
    - How to Contribute to RetroDECK?: wiki_helping/contibute-rd
    - How to help out with testing?: wiki_helping/testing-rd.md

theme: readthedocs
