name: "Runner Cleanup"

on:
  workflow_dispatch:

jobs:
  Cleanup:
    runs-on: self-hosted
    steps:
    - name: Self Hosted Runner Post Job Cleanup Action
      uses: TooMuch4U/actions-clean@v2.1
            